In [1]:
import torch

In [2]:
def activation(x):
    """
    sigmoid activate function
    arguments:
    x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [9]:
#Genarate some dat
torch.manual_seed(7) # setting the random seeds so things are predictable 
#Features are 5 random normal variables 
features = torch.randn((1,5))
#true weights for data, normal variables again
weights = torch.randn_like(features)
#and a true bias term
bias = torch.randn((1,1))

In [10]:
print('Features: ', features)
print('Weights:', weights)
print('Bias: ', bias)

Features:  tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Weights: tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Bias:  tensor([[0.3177]])


In [11]:
torch.sum(features)

tensor(2.1626)

In [12]:
print('Reshape: ', weights.reshape(1,5))
print('Reshape row as column: ', weights.reshape(5,1))
print('Resize: ', weights.resize(1,5))
print('Resize: ', weights.resize_(1,4))
print('Resize: ', weights.resize_(2,3))
print('Resize row as column: ', weights.resize_(5,1))
#we are gonna use view method for more precesion 
print('View: ', weights.view(1,5))
print('View row as column: ', weights.view(5,1))

Reshape:  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Reshape row as column:  tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
Resize:  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Resize:  tensor([[-0.8948, -0.3556,  1.2324,  0.1382]])
Resize:  tensor([[-0.8948, -0.3556,  1.2324],
        [ 0.1382, -1.6822,  0.0000]])
Resize row as column:  tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
View:  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
View row as column:  tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])


In [13]:
print('shape:',features.shape)
weights.size() #getting the sizes
#We can see shape of tensors in both ways

shape: torch.Size([1, 5])


torch.Size([5, 1])

In [14]:
# calculation output y for our input features
"""
output = sigmoid(sum(features*weights) + bias)

"""
y = activation(torch.sum(features*weights) + bias) # torch version
y1 = activation((features*weights).sum() + bias) # sum like numpy

In [15]:
print(y)
print("sum in another way: ", y1)

tensor([[0.0448]])
sum in another way:  tensor([[0.0448]])


In [16]:
# calculating matrix multiplication using matrix multiplication
y = activation(torch.mm(features, weights.view(5,1) ) + bias)
y

tensor([[0.1595]])

In [17]:
#We can also use torch.matmul() for matrix multiplication
y = activation(torch.matmul(features, weights.view(5,1) ) + bias)
y

tensor([[0.1595]])

In [18]:
print("This is the first code to approach Neural network with pytorch")

This is the first code to approach Neural network with pytorch
