In [22]:
print("This code illustrate that how can we convert numpy into tensor and get back numpy from tensor")

This code illustrate that how can we convert numpy into tensor and get back numpy from tensor


In [23]:
import numpy as np
import torch

In [24]:
a = np.random.randn(4,3)
print(a)
print(type(a))

[[-0.67664056  2.27055623  0.93614609]
 [ 1.66283167 -0.54097684 -0.17603564]
 [-1.28758421 -0.93727703 -0.70542708]
 [ 0.25671682  0.15446687  0.92397226]]
<class 'numpy.ndarray'>


In [25]:
b = torch.from_numpy(a)
print(b)
print(type(b))

tensor([[-0.6766,  2.2706,  0.9361],
        [ 1.6628, -0.5410, -0.1760],
        [-1.2876, -0.9373, -0.7054],
        [ 0.2567,  0.1545,  0.9240]], dtype=torch.float64)
<class 'torch.Tensor'>


In [26]:
b.numpy()
c= b.numpy()
print(c)
print(type(c))

[[-0.67664056  2.27055623  0.93614609]
 [ 1.66283167 -0.54097684 -0.17603564]
 [-1.28758421 -0.93727703 -0.70542708]
 [ 0.25671682  0.15446687  0.92397226]]
<class 'numpy.ndarray'>


In [27]:
b.mul_(3)

tensor([[-2.0299,  6.8117,  2.8084],
        [ 4.9885, -1.6229, -0.5281],
        [-3.8628, -2.8118, -2.1163],
        [ 0.7702,  0.4634,  2.7719]], dtype=torch.float64)

In [28]:
print(b)
print(type(b))
c = c*3
print(c)
print(type(c))

tensor([[-2.0299,  6.8117,  2.8084],
        [ 4.9885, -1.6229, -0.5281],
        [-3.8628, -2.8118, -2.1163],
        [ 0.7702,  0.4634,  2.7719]], dtype=torch.float64)
<class 'torch.Tensor'>
[[ -6.08976504  20.43500604   8.42531482]
 [ 14.96548503  -4.86879159  -1.58432075]
 [-11.5882579   -8.43549324  -6.34884373]
 [  2.31045134   1.39020183   8.31575032]]
<class 'numpy.ndarray'>


In [29]:
a
# Numpy array matches new values from Tensor
# The memory is shared between the Numpy array and Torch tensor,
# so if you change the values in-place of one object, the other will change as well.

array([[-2.02992168,  6.81166868,  2.80843827],
       [ 4.98849501, -1.62293053, -0.52810692],
       [-3.86275263, -2.81183108, -2.11628124],
       [ 0.77015045,  0.46340061,  2.77191677]])